version: "3.8"
services:
  server:
    image: akeedm/bookexchangeserver:latest
    ports:
      - "5000:5000"
    environment:
      DB_NAME: bookexchange
      DB_USER: akeed
      DB_PASSWORD: akeed123
      DB_HOST: db
      DB_PORT: 5432
      PORT: 5000
      JWT_SECRET: book_exchange_jwt
    depends_on:
      db:
        condition: service_healthy

  ui:
    image: akeedm/bookexchangeui:latest
    ports:
      - "80:80"
    environment:
      API_URL: http://localhost:5000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: akeed
      POSTGRES_PASSWORD: akeed123
      POSTGRES_DB: bookexchange
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akeed -d bookexchange"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
