name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get EC2 Public IP
        id: get_ip
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=BookExchangeServerInstance" --query "Reservations[*].Instances[*].InstanceId" --output text)
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
          echo "::set-output name=public_ip::$PUBLIC_IP"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          PUBLIC_IP: ${{ env.PUBLIC_IP }}
        run: |
          # Create a temporary file for the private key
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

           # Execute SSH command
          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@$PUBLIC_IP << 'EOF'
            cd /usr/app
            sudo docker-compose pull
            sudo docker-compose up -d
          EOF

          # Clean up the private key file
          rm private_key.pem
