name: Build and Push Docker Image Backend

on:
  push:
    branches:
      - develop
    paths:
      - "backend/Dockerfile" # Trigger workflow if Dockerfile changes
      - "backend/src/**" # Trigger workflow if any file in the src directory changes
      - "backend/package.json"
      - "docker-compose.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: akeedm/bookexchangeserver:latest
